server:
  port: 8080
  servlet:
    context-path: /myapp

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: my-spring-boot-app
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    queue:
      order:
        input: ${QUEUE_INPUT_ORDER:input_order}
        input-dlq: ${QUEUE_INPUT_ORDER:input_order_dlq}
        output: ${QUEUE_OUTPUT_ORDER:output_order}
    exchange:
      order: ${DEAD_LETTER_EXCHANGE:dead_letter_exchange}
    routing-key:
      order: ${ROUTING_KEY_DLQ:dlq.routing.key}

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

factory:
  url: http://localhost:7455/example

logging:
  level:
    root: info
    com.example.myapp: debug
#    org.springframework.boot: DEBUG

management:
  parameters:
    time-verification: ${TIME_VERIFICATION_SECONDS:3600}
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      logging:
        enabled: true